import type { Metadata } from "next";

import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";
import Form from "@/components/Form";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <section className="flex justify-center py-10 px-8">
          <Form />
        </section>
        <Footer />
      </body>
    </html>
  );
}
